version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: people_api
      MYSQL_USER: db_user
      MYSQL_PASSWORD: password
    ports:
      - "3333:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "8088:8088"
    depends_on:
      - mysql

volumes:
  mysql_data:
