CREATE TABLE IF NOT EXISTS people (
    ID VARCHAR(25) NOT NULL PRIMARY KEY,
    Name VARCHAR(25) NOT NULL,
    LastName VARCHAR(25) NOT NULL,
    Email VARCHAR(50) NOT NULL UNIQUE,
    Telephone VARCHAR(20) NOT NULL,
    Country VARCHAR(5) NOT NULL,
    State VARCHAR(10) NOT NULL
    );